## Program: VMTK
## Language:  Python
## Date:      January 30, 2018
## Version:   1.4

##   Copyright (c) Richard Izzo, Luca Antiga, All rights reserved.
##   See LICENSE file for details.

##      This software is distributed WITHOUT ANY WARRANTY; without even
##      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##      PURPOSE.  See the above copyright notices for more information.

## Note: this code was contributed by
##       Richard Izzo (Github @rlizzo)
##       University at Buffalo

python:
  - 3.13
  - 3.12
  - 3.11

vtk:
  - 9.5.*

itk:
  - 5.4.*

numpy:
  - 1.26

pin_run_as_build:
  python:
    max_pin: x.x.x
    min_pin: x.x
  vtk: x.x.x
  itk: x.x.x

c_compiler:
  - vs2022           # [win]

cxx_compiler:
  - vs2022           # [win]

CONDA_BUILD_SYSROOT:
  - $HOME/MacOSX-SDKs/MacOSX14.0.sdk   # [osx]
